version: "3.8"
services:
  questions_microservice:
    build: .
    restart: always
    ports:
      - 8089:8089
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: questions_microservice
      MYSQL_USER: hammad
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQM


